### ISSUE TITLE
Decide which version of K to use

### ISSUE THREAD

**Issue by dfilaretti** [kframework/solidity-semantics#10]
Shall we just build from source and always get latest? 
Or use one of the stable builds?

**Comment by herrBez** [comment]
Which version of K do you use?

**Comment by dfilaretti** [comment]
We are using the latest K compiled from source. 
You should get the repo (https://github.com/kframework/k) and build it from source by following the instructions that are listed there. 

This issue was opened because there was a discussion about which K revision to use, but eventually we decided to stick to the cutting edge / latest version.
