### ISSUE TITLE
Execution stuck on `run` starting at K commit `cff1ca0e49c39ede21c66ab06a0692d98df2ff1c`

### ISSUE THREAD

**Issue by dfilaretti** [kframework/solidity-semantics#45]
We recently started to notice that execution of previously working tests now got stuck on the `run` term. 
After a search on K history, we realized the problem is introduced in commit `cff1ca0e49c39ede21c66ab06a0692d98df2ff1c`. 

The commit immediately before that (`4935faab5333f6f83d82413bd7c63b2d5b1461b2`) does not show the problem.

**Comment by ehildenb** [comment]
@dfilaretti I think (if you have time) the proper thing to do is boil down a minimal example and submit as an issue to the kframework/k repo instead.

**Comment by dfilaretti** [comment]
While trying to debug this I noticed something odd. 

It gets stuck with:

```
#run "Test1" : { 
  "exec" : { "code" : ...,  .JSONList } , 
  .JSONList 
}
```

while the rule that is supposed to apply is (NB: `#execKeys` is basically just `"exec"`) :

```
rule #run TESTID : {
  KEY:(VAL:JSON), 
  NEXT , 
  REST:JSONList
} => #run TESTID : { NEXT, KEY:VAL , REST}
     requires KEY in #execKeys
```

so I am not surprised it doesn't work.
I am not sure why it actually used to work before. 

Anyway I added a second rule to handle this case (removing `NEXT`):

```
rule #run TESTID : {
  KEY:(VAL:JSON), 
  REST:JSONList
}   => #run TESTID : { KEY:VAL }
requires KEY in #execKeys
```

and this seems to work. 

After that, there were a couple of similar issues, which I fixed similarly (see #47).

**Comment by dfilaretti** [comment]
Note to self: branch `debug-stuck-execution` contains stripped-down version of the semantics (that still shows this issue), in case it turns out that we are dealing with an actual K problem.

**Comment by dfilaretti** [comment]
I was looking into the specific K change after which we started to see the problem (https://github.com/kframework/k/pull/184) and I noticed that some behavior has been changed and the tutorials updated accordingly (https://github.com/kframework/k/pull/184/commits/2d7f0aadd8c1b5c315ec510d1acb61faaf89dbbb). 

It seems that instead of using `.Ids`, `.Vals` etc. as before, they now add new sorts `Bottom`/`Bottoms` and use `.Bottoms` everywhere (see commit linked above). 

I'm not 100% sure of why this change was made and what it's supposed to fix, but it appears to me to be related to the current issue somehow (see my quick fix https://github.com/kframework/solidity-semantics/pull/47).

What do you think @ehildenb ? Should we also switch to "`.Bottoms`-only" as in the modified tutorials? Or is it unrelated?
